defmodule Cs.Repo.Migrations.MigrateResources12 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:variable_environments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :value, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :variable_id,
          references(:variables,
            column: :id,
            name: "variable_environments_variable_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :environment_id,
          references(:environments,
            column: :id,
            name: "variable_environments_environment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :secret_value, :binary
    end

    create unique_index(:variable_environments, [:environment_id, :variable_id],
             name: "variable_environments_unique_link_index"
           )

    execute("""
    INSERT INTO variable_environments (
      id,
      variable_id,
      environment_id,
      secret_value,
      created_at,
      updated_at
    )
    SELECT
      gen_random_uuid(),
      id,
      environment_id,
      encrypted_value,
      created_at,
      updated_at
    FROM variables
    WHERE environment_id IS NOT NULL
    """)

    alter table(:variables) do
      remove :encrypted_value
      remove :environment_id
    end

    drop_if_exists unique_index(:variables, [:environment_id, :name],
                     name: "variables_unique_name_per_environment_index"
                   )

    alter table(:variables) do
      modify :name, :citext
    end

    create unique_index(:variables, [:name], name: "variables_unique_name_index")

    alter table(:environments) do
      modify :name, :citext
    end

    alter table(:commands) do
      modify :name, :citext
    end
  end

  def down do
    alter table(:commands) do
      modify :name, :text
    end

    alter table(:environments) do
      modify :name, :text
    end

    drop_if_exists unique_index(:variable_environments, [:environment_id, :variable_id],
                     name: "variable_environments_unique_link_index"
                   )

    drop constraint(:variable_environments, "variable_environments_variable_id_fkey")

    drop constraint(:variable_environments, "variable_environments_environment_id_fkey")

    drop table(:variable_environments)

    drop_if_exists unique_index(:variables, [:name], name: "variables_unique_name_index")

    alter table(:variables) do
      modify :name, :text
    end

    create unique_index(:variables, [:environment_id, :name],
             name: "variables_unique_name_per_environment_index"
           )

    alter table(:variables) do
      add :environment_id,
          references(:environments,
            column: :id,
            name: "variables_environment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :encrypted_value, :binary, null: false
    end
  end
end
