defmodule Cs.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:command_schedules) do
      add :enabled, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:command_schedules) do
      remove :enabled
    end
  end
end
