defmodule Cs.Repo.Migrations.MigrateResources16 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:variables) do
      remove :encrypted_value
      modify :secret_value, :text
      add :value, :text
    end
  end

  def down do
    alter table(:variables) do
      remove :value
      modify :secret_value, :binary
      add :encrypted_value, :binary
    end
  end
end
