defmodule Cs.Repo.Migrations.MigrateResources15 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'variables'
          AND column_name = 'encrypted_secret_value'
      ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'variables'
          AND column_name = 'secret_value'
      ) THEN
        ALTER TABLE variables RENAME COLUMN encrypted_secret_value TO secret_value;
      END IF;
    END
    $$;
    """)
  end

  def down do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'variables'
          AND column_name = 'secret_value'
      ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'variables'
          AND column_name = 'encrypted_secret_value'
      ) THEN
        ALTER TABLE variables RENAME COLUMN secret_value TO encrypted_secret_value;
      END IF;
    END
    $$;
    """)
  end
end
