defmodule Cs.Repo.Migrations.MigrateResources13 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:variables) do
      add :description, :text
      add :encrypted_value, :binary
    end

    drop_if_exists unique_index(:variables, [:name], name: "variables_unique_name_index")

    execute("""
    UPDATE variables
    SET encrypted_value = ve.secret_value
    FROM variable_environments ve
    WHERE ve.variable_id = variables.id
      AND ve.secret_value IS NOT NULL
      AND variables.encrypted_value IS NULL
    """)

    alter table(:variable_environments) do
      remove :secret_value
      remove :value
    end
  end

  def down do
    alter table(:variable_environments) do
      add :value, :text
      add :secret_value, :binary
    end

    create unique_index(:variables, [:name], name: "variables_unique_name_index")

    alter table(:variables) do
      remove :encrypted_value
      remove :description
    end
  end
end
