defmodule Cs.Repo.Migrations.MigrateResources14 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:variables) do
      add :secret_value, :binary
    end
  end

  def down do
    alter table(:variables) do
      remove :secret_value
    end
  end
end
