defmodule Cs.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:command_job_events) do
      add :command_text, :text, null: false, default: "(legacy event: command text unavailable)"
    end
  end

  def down do
    alter table(:command_job_events) do
      remove :command_text
    end
  end
end
