defmodule Cs.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:command_job_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false
      add :started_at, :utc_datetime_usec, null: false
      add :finished_at, :utc_datetime_usec
      add :duration_ms, :bigint
      add :stdout, :text, null: false, default: ""
      add :stderr, :text, null: false, default: ""

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :command_job_id,
          references(:command_jobs,
            column: :id,
            name: "command_job_events_command_job_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:command_job_events, [:status, :started_at])

    create index(:command_job_events, [:command_job_id, :started_at])
  end

  def down do
    drop constraint(:command_job_events, "command_job_events_command_job_id_fkey")

    drop_if_exists index(:command_job_events, [:command_job_id, :started_at])

    drop_if_exists index(:command_job_events, [:status, :started_at])

    drop table(:command_job_events)
  end
end
