defmodule Cs.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(
                     :command_schedule_environments,
                     [:command_schedule_id, :environment_id],
                     name: "cmd_sched_env_uidx"
                   )

    create unique_index(:command_schedule_environments, [:environment_id, :command_schedule_id],
             name: "command_schedule_environments_unique_link_index"
           )

    drop_if_exists unique_index(:command_schedule_crons, [:command_schedule_id, :cron_id],
                     name: "cmd_sched_cron_uidx"
                   )

    create unique_index(:command_schedule_crons, [:cron_id, :command_schedule_id],
             name: "command_schedule_crons_unique_link_index"
           )
  end

  def down do
    drop_if_exists unique_index(:command_schedule_crons, [:cron_id, :command_schedule_id],
                     name: "command_schedule_crons_unique_link_index"
                   )

    create unique_index(:command_schedule_crons, [:command_schedule_id, :cron_id],
             name: "cmd_sched_cron_uidx"
           )

    drop_if_exists unique_index(
                     :command_schedule_environments,
                     [:environment_id, :command_schedule_id],
                     name: "command_schedule_environments_unique_link_index"
                   )

    create unique_index(:command_schedule_environments, [:command_schedule_id, :environment_id],
             name: "cmd_sched_env_uidx"
           )
  end
end
