defmodule Cs.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:command_jobs) do
      modify :oban_job_id, :bigint, null: true
    end
  end

  def down do
    alter table(:command_jobs) do
      modify :oban_job_id, :bigint, null: false
    end
  end
end
