defmodule Cns.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:environments) do
      add :enabled, :boolean, null: false, default: true
    end

    create table(:crons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :crontab_expression, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:crons, [:name], name: "crons_unique_name_index")

    alter table(:commands) do
      remove :environment_id
      remove :cron_expression
    end

    drop_if_exists unique_index(:commands, [:environment_id, :name],
                     name: "commands_unique_name_per_environment_index"
                   )

    create unique_index(:commands, [:name], name: "commands_unique_name_index")

    create table(:command_schedules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :command_id,
          references(:commands,
            column: :id,
            name: "command_schedules_command_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create table(:command_schedule_environments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :command_schedule_id,
          references(:command_schedules,
            column: :id,
            name: "command_schedule_environments_command_schedule_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :environment_id,
          references(:environments,
            column: :id,
            name: "command_schedule_environments_environment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:command_schedule_environments, [:command_schedule_id, :environment_id],
             name: "cmd_sched_env_uidx"
           )

    create table(:command_schedule_crons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :command_schedule_id,
          references(:command_schedules,
            column: :id,
            name: "command_schedule_crons_command_schedule_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :cron_id,
          references(:crons,
            column: :id,
            name: "command_schedule_crons_cron_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:command_schedule_crons, [:command_schedule_id, :cron_id],
             name: "cmd_sched_cron_uidx"
           )
  end

  def down do
    drop_if_exists unique_index(:command_schedule_crons, [:command_schedule_id, :cron_id],
                     name: "cmd_sched_cron_uidx"
                   )

    drop constraint(:command_schedule_crons, "command_schedule_crons_command_schedule_id_fkey")

    drop constraint(:command_schedule_crons, "command_schedule_crons_cron_id_fkey")

    drop table(:command_schedule_crons)

    drop_if_exists unique_index(
                     :command_schedule_environments,
                     [:command_schedule_id, :environment_id], name: "cmd_sched_env_uidx")

    drop constraint(
           :command_schedule_environments,
           "command_schedule_environments_command_schedule_id_fkey"
         )

    drop constraint(
           :command_schedule_environments,
           "command_schedule_environments_environment_id_fkey"
         )

    drop table(:command_schedule_environments)

    drop constraint(:command_schedules, "command_schedules_command_id_fkey")

    drop table(:command_schedules)

    drop_if_exists unique_index(:commands, [:name], name: "commands_unique_name_index")

    create unique_index(:commands, [:environment_id, :name],
             name: "commands_unique_name_per_environment_index"
           )

    alter table(:commands) do
      add :cron_expression, :text, null: false

      add :environment_id,
          references(:environments,
            column: :id,
            name: "commands_environment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    drop_if_exists unique_index(:crons, [:name], name: "crons_unique_name_index")

    drop table(:crons)

    alter table(:environments) do
      remove :enabled
    end
  end
end
