defmodule Cns.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:command_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :oban_job_id, :bigint, null: false
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :command_id,
          references(:commands,
            column: :id,
            name: "command_jobs_command_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :environment_id,
          references(:environments,
            column: :id,
            name: "command_jobs_environment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :cron_id,
          references(:crons,
            column: :id,
            name: "command_jobs_cron_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:command_jobs, [:oban_job_id],
             name: "command_jobs_unique_oban_job_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:command_jobs, [:oban_job_id],
                     name: "command_jobs_unique_oban_job_id_index"
                   )

    drop constraint(:command_jobs, "command_jobs_command_id_fkey")

    drop constraint(:command_jobs, "command_jobs_environment_id_fkey")

    drop constraint(:command_jobs, "command_jobs_cron_id_fkey")

    drop table(:command_jobs)
  end
end
