defmodule Cns.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:command_jobs) do
      add :shell_command, :text, null: false, default: ""
      add :cron_expression, :text, null: false, default: ""
    end

    alter table(:command_job_events) do
      remove :command_text
    end
  end

  def down do
    alter table(:command_job_events) do
      add :command_text, :text, null: false
    end

    alter table(:command_jobs) do
      remove :cron_expression
      remove :shell_command
    end
  end
end
