defmodule Cns.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:command_job_events) do
      modify :started_at, :utc_datetime_usec, null: true
    end
  end

  def down do
    alter table(:command_job_events) do
      modify :started_at, :utc_datetime_usec, null: false
    end
  end
end
