defmodule Cns.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:variables, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :environment_id, :uuid, null: false
      add :encrypted_value, :binary, null: false
    end

    create table(:environments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:variables) do
      modify :environment_id,
             references(:environments,
               column: :id,
               name: "variables_environment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:variables, [:environment_id, :name],
             name: "variables_unique_name_per_environment_index"
           )

    alter table(:environments) do
      add :name, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:environments, [:name], name: "environments_unique_name_index")

    create table(:commands, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :shell_command, :text, null: false
      add :cron_expression, :text, null: false
      add :enabled, :boolean, null: false, default: true
      add :timeout_ms, :bigint, null: false, default: 60000

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :environment_id,
          references(:environments,
            column: :id,
            name: "commands_environment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:commands, [:environment_id, :name],
             name: "commands_unique_name_per_environment_index"
           )

    create table(:command_execution_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false
      add :started_at, :utc_datetime_usec, null: false
      add :finished_at, :utc_datetime_usec
      add :duration_ms, :bigint
      add :stdout, :text, null: false, default: ""
      add :stderr, :text, null: false, default: ""

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :command_id,
          references(:commands,
            column: :id,
            name: "command_execution_events_command_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:command_execution_events, [:status, :started_at])

    create index(:command_execution_events, [:command_id, :started_at])
  end

  def down do
    drop constraint(:command_execution_events, "command_execution_events_command_id_fkey")

    drop_if_exists index(:command_execution_events, [:command_id, :started_at])

    drop_if_exists index(:command_execution_events, [:status, :started_at])

    drop table(:command_execution_events)

    drop_if_exists unique_index(:commands, [:environment_id, :name],
                     name: "commands_unique_name_per_environment_index"
                   )

    drop constraint(:commands, "commands_environment_id_fkey")

    drop table(:commands)

    drop_if_exists unique_index(:environments, [:name], name: "environments_unique_name_index")

    alter table(:environments) do
      remove :updated_at
      remove :created_at
      remove :name
    end

    drop_if_exists unique_index(:variables, [:environment_id, :name],
                     name: "variables_unique_name_per_environment_index"
                   )

    drop constraint(:variables, "variables_environment_id_fkey")

    alter table(:variables) do
      modify :environment_id, :uuid
    end

    drop table(:environments)

    drop table(:variables)
  end
end
