// Generated by AshTypescript
// Do not edit this file manually





export type UUID = string;
export type UtcDateTimeUsec = string;

// Environment Schema
export type EnvironmentResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name";
  id: UUID;
  name: string;
  variables: { __type: "Relationship"; __array: true; __resource: VariableResourceSchema; };
  commands: { __type: "Relationship"; __array: true; __resource: CommandResourceSchema; };
};



export type EnvironmentAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name";
  id: UUID;
  name: string;
};


// Variable Schema
export type VariableResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "environmentId" | "value";
  id: UUID;
  name: string;
  environmentId: UUID;
  value: string;
  environment: { __type: "Relationship"; __resource: EnvironmentResourceSchema; };
};



export type VariableAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "environmentId";
  id: UUID;
  name: string;
  environmentId: UUID;
};


// Command Schema
export type CommandResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "shellCommand" | "cronExpression" | "enabled" | "timeoutMs" | "environmentId";
  id: UUID;
  name: string;
  shellCommand: string;
  cronExpression: string;
  enabled: boolean;
  timeoutMs: number;
  environmentId: UUID;
  environment: { __type: "Relationship"; __resource: EnvironmentResourceSchema; };
  executionEvents: { __type: "Relationship"; __array: true; __resource: CommandExecutionEventResourceSchema; };
};



export type CommandAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "shellCommand" | "cronExpression" | "enabled" | "timeoutMs" | "environmentId";
  id: UUID;
  name: string;
  shellCommand: string;
  cronExpression: string;
  enabled: boolean;
  timeoutMs: number;
  environmentId: UUID;
};


// CommandExecutionEvent Schema
export type CommandExecutionEventResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "status" | "startedAt" | "finishedAt" | "durationMs" | "stdout" | "stderr" | "commandId";
  id: UUID;
  status: string;
  startedAt: UtcDateTimeUsec;
  finishedAt: UtcDateTimeUsec | null;
  durationMs: number | null;
  stdout: string;
  stderr: string;
  commandId: UUID;
  command: { __type: "Relationship"; __resource: CommandResourceSchema; };
};



export type CommandExecutionEventAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "status" | "startedAt" | "finishedAt" | "durationMs" | "stdout" | "stderr" | "commandId";
  id: UUID;
  status: string;
  startedAt: UtcDateTimeUsec;
  finishedAt: UtcDateTimeUsec | null;
  durationMs: number | null;
  stdout: string;
  stderr: string;
  commandId: UUID;
};




export type EnvironmentFilterInput = {
  and?: Array<EnvironmentFilterInput>;
  or?: Array<EnvironmentFilterInput>;
  not?: Array<EnvironmentFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };


  variables?: VariableFilterInput;

  commands?: CommandFilterInput;

};
export type VariableFilterInput = {
  and?: Array<VariableFilterInput>;
  or?: Array<VariableFilterInput>;
  not?: Array<VariableFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  environmentId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  value?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };


  environment?: EnvironmentFilterInput;

};
export type CommandFilterInput = {
  and?: Array<CommandFilterInput>;
  or?: Array<CommandFilterInput>;
  not?: Array<CommandFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  shellCommand?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  cronExpression?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  enabled?: {
    eq?: boolean;
    notEq?: boolean;
  };

  timeoutMs?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  environmentId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  environment?: EnvironmentFilterInput;

  executionEvents?: CommandExecutionEventFilterInput;

};
export type CommandExecutionEventFilterInput = {
  and?: Array<CommandExecutionEventFilterInput>;
  or?: Array<CommandExecutionEventFilterInput>;
  not?: Array<CommandExecutionEventFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  status?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  startedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  finishedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  durationMs?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  stdout?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  stderr?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  commandId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  command?: CommandFilterInput;

};


// Utility Types

// Resource schema constraint
export type TypedSchema = {
  __type: "Resource" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
export type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends UnionSchema["__primitiveFields"]
      ? FieldSelection[FieldIndex] extends keyof UnionSchema
        ? { [P in FieldSelection[FieldIndex]]: UnionSchema[FieldSelection[FieldIndex]] }
        : never
      : FieldSelection[FieldIndex] extends Record<string, any>
        ? {
            [UnionKey in keyof FieldSelection[FieldIndex]]: UnionKey extends keyof UnionSchema
              ? NonNullable<UnionSchema[UnionKey]> extends { __array: true; __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                ? FieldSelection[FieldIndex][UnionKey] extends any[]
                  ? Array<
                      UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      >
                    > | null
                  : never
                : NonNullable<UnionSchema[UnionKey]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                  ? FieldSelection[FieldIndex][UnionKey] extends any[]
                    ? UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      > | null
                    : never
                  : NonNullable<UnionSchema[UnionKey]> extends TypedSchema
                    ? InferResult<NonNullable<UnionSchema[UnionKey]>, FieldSelection[FieldIndex][UnionKey]>
                    : never
              : never;
          }
        : never;
  }[number]
>;

export type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

export type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

export type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

export type ComplexFieldSelection<T extends TypedSchema> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? UnifiedFieldSelection<NonNullable<Resource>>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>>[] }
          : never
      : T[K] extends { __type: "TypedMap" }
        ? NonNullable<T[K]> extends TypedSchema
          ? UnifiedFieldSelection<NonNullable<T[K]>>[]
          : never
        : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
          ? T[K] extends { __array: true }
            ? (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : NonNullable<T[K]> extends TypedSchema
              ? UnifiedFieldSelection<NonNullable<T[K]>>[]
              : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
export type UnifiedFieldSelection<T extends TypedSchema> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T>; // Recursive case

export type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? T[K] extends { __array: true }
                ? Array<InferResult<NonNullable<Resource>, Field[K]>>
                : null extends Resource
                  ? InferResult<NonNullable<Resource>, Field[K]> | null
                  : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : NonNullable<T[K]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
              ? NonNullable<T[K]> extends { __array: true }
                ? Field[K] extends any[]
                  ? null extends T[K]
                    ? Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      > | null
                    : Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      >
                  : never
                : Field[K] extends any[]
                  ? null extends T[K]
                    ? UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof NonNullable<T[K]>
                                ? { [P in E]: NonNullable<T[K]>[P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      > | null
                    : UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof T[K]
                                ? { [P in E]: T[K][P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      >
                  : never
              : T[K] extends { __type: "Union"; __primitiveFields: any }
                ? T[K] extends { __array: true }
                  ? Field[K] extends any[]
                    ? null extends T[K]
                      ? Array<InferUnionFieldValue<T[K], Field[K]>> | null
                      : Array<InferUnionFieldValue<T[K], Field[K]>>
                    : never
                  : Field[K] extends any[]
                    ? null extends T[K]
                      ? InferUnionFieldValue<T[K], Field[K]> | null
                      : InferUnionFieldValue<T[K], Field[K]>
                    : never
                  : NonNullable<T[K]> extends TypedSchema
                    ? null extends T[K]
                      ? InferResult<NonNullable<T[K]>, Field[K]> | null
                      : InferResult<NonNullable<T[K]>, Field[K]>
                    : never
          : never;
      }
    : never;

export type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters
export type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  false;

// Infer which pagination type is being used from the page config
export type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
export type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call.
 *
 * This type matches the error structure defined in the AshTypescript.Rpc.Error protocol.
 *
 * @example
 * const error: AshRpcError = {
 *   type: "invalid_changes",
 *   message: "Invalid value for field %{field}",
 *   shortMessage: "Invalid changes",
 *   vars: { field: "email" },
 *   fields: ["email"],
 *   path: ["user", "email"],
 *   details: { suggestion: "Provide a valid email address" }
 * }
 */
export type AshRpcError = {
  /** Machine-readable error type (e.g., "invalid_changes", "not_found") */
  type: string;
  /** Full error message (may contain template variables like %{key}) */
  message: string;
  /** Concise version of the message */
  shortMessage: string;
  /** Variables to interpolate into the message template */
  vars: Record<string, any>;
  /** List of affected field names (for field-level errors) */
  fields: string[];
  /** Path to the error location in the data structure */
  path: string[];
  /** Optional map with extra details (e.g., suggestions, hints) */
  details?: Record<string, any>;
}

/**
 * Represents the result of a validation RPC call.
 *
 * All validation actions return this same structure, indicating either
 * successful validation or a list of validation errors.
 *
 * @example
 * // Successful validation
 * const result: ValidationResult = { success: true };
 *
 * // Failed validation
 * const result: ValidationResult = {
 *   success: false,
 *   errors: [
 *     {
 *       type: "required",
 *       message: "is required",
 *       shortMessage: "Required field",
 *       vars: { field: "email" },
 *       fields: ["email"],
 *       path: []
 *     }
 *   ]
 * };
 */
export type ValidationResult =
  | { success: true }
  | { success: false; errors: AshRpcError[]; };





// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/api/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
export async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/api/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}









export type ListEnvironmentsFields = UnifiedFieldSelection<EnvironmentResourceSchema>[];


export type InferListEnvironmentsResult<
  Fields extends ListEnvironmentsFields | undefined,
  Page extends ListEnvironmentsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<EnvironmentResourceSchema, Fields>>, {
  results: Array<InferResult<EnvironmentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<EnvironmentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListEnvironmentsConfig = {
  tenant?: string;
  fields: ListEnvironmentsFields;
  filter?: EnvironmentFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListEnvironmentsResult<Fields extends ListEnvironmentsFields, Page extends ListEnvironmentsConfig["page"] = undefined> = | { success: true; data: InferListEnvironmentsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Environment records
 *
 * @ashActionType :read
 */
export async function listEnvironments<Fields extends ListEnvironmentsFields, Config extends ListEnvironmentsConfig = ListEnvironmentsConfig>(
  config: Config & { fields: Fields }
): Promise<ListEnvironmentsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_environments",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListEnvironmentsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Environment records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListEnvironments(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_environments",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateEnvironmentInput = {
  name: string;
};

export type CreateEnvironmentFields = UnifiedFieldSelection<EnvironmentResourceSchema>[];

export type InferCreateEnvironmentResult<
  Fields extends CreateEnvironmentFields | undefined,
> = InferResult<EnvironmentResourceSchema, Fields>;

export type CreateEnvironmentResult<Fields extends CreateEnvironmentFields | undefined = undefined> = | { success: true; data: InferCreateEnvironmentResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Environment
 *
 * @ashActionType :create
 */
export async function createEnvironment<Fields extends CreateEnvironmentFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateEnvironmentInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateEnvironmentResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_environment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateEnvironmentResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Environment
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateEnvironment(
  config: {
  tenant?: string;
  input: CreateEnvironmentInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_environment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateEnvironmentInput = {
  name?: string;
};

export type UpdateEnvironmentFields = UnifiedFieldSelection<EnvironmentResourceSchema>[];

export type InferUpdateEnvironmentResult<
  Fields extends UpdateEnvironmentFields | undefined,
> = InferResult<EnvironmentResourceSchema, Fields>;

export type UpdateEnvironmentResult<Fields extends UpdateEnvironmentFields | undefined = undefined> = | { success: true; data: InferUpdateEnvironmentResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Environment
 *
 * @ashActionType :update
 */
export async function updateEnvironment<Fields extends UpdateEnvironmentFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: UpdateEnvironmentInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateEnvironmentResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_environment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateEnvironmentResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Environment
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateEnvironment(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: UpdateEnvironmentInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_environment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}



export type DestroyEnvironmentResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Environment
 *
 * @ashActionType :destroy
 */
export async function destroyEnvironment(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyEnvironmentResult> {
  const payload = {
    action: "destroy_environment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyEnvironmentResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Environment
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyEnvironment(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "destroy_environment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListVariablesFields = UnifiedFieldSelection<VariableResourceSchema>[];


export type InferListVariablesResult<
  Fields extends ListVariablesFields | undefined,
  Page extends ListVariablesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<VariableResourceSchema, Fields>>, {
  results: Array<InferResult<VariableResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<VariableResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListVariablesConfig = {
  tenant?: string;
  fields: ListVariablesFields;
  filter?: VariableFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListVariablesResult<Fields extends ListVariablesFields, Page extends ListVariablesConfig["page"] = undefined> = | { success: true; data: InferListVariablesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Variable records
 *
 * @ashActionType :read
 */
export async function listVariables<Fields extends ListVariablesFields, Config extends ListVariablesConfig = ListVariablesConfig>(
  config: Config & { fields: Fields }
): Promise<ListVariablesResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_variables",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListVariablesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Variable records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListVariables(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_variables",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateVariableInput = {
  name: string;
  environmentId: UUID;
  value?: string;
};

export type CreateVariableFields = UnifiedFieldSelection<VariableResourceSchema>[];

export type InferCreateVariableResult<
  Fields extends CreateVariableFields | undefined,
> = InferResult<VariableResourceSchema, Fields>;

export type CreateVariableResult<Fields extends CreateVariableFields | undefined = undefined> = | { success: true; data: InferCreateVariableResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Variable
 *
 * @ashActionType :create
 */
export async function createVariable<Fields extends CreateVariableFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateVariableInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateVariableResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_variable",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateVariableResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Variable
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateVariable(
  config: {
  tenant?: string;
  input: CreateVariableInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_variable",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateVariableInput = {
  name?: string;
  value?: string;
};

export type UpdateVariableFields = UnifiedFieldSelection<VariableResourceSchema>[];

export type InferUpdateVariableResult<
  Fields extends UpdateVariableFields | undefined,
> = InferResult<VariableResourceSchema, Fields>;

export type UpdateVariableResult<Fields extends UpdateVariableFields | undefined = undefined> = | { success: true; data: InferUpdateVariableResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Variable
 *
 * @ashActionType :update
 */
export async function updateVariable<Fields extends UpdateVariableFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: UpdateVariableInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateVariableResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_variable",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateVariableResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Variable
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateVariable(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: UpdateVariableInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_variable",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}



export type DestroyVariableResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Variable
 *
 * @ashActionType :destroy
 */
export async function destroyVariable(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyVariableResult> {
  const payload = {
    action: "destroy_variable",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyVariableResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Variable
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyVariable(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "destroy_variable",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListCommandsFields = UnifiedFieldSelection<CommandResourceSchema>[];


export type InferListCommandsResult<
  Fields extends ListCommandsFields | undefined,
  Page extends ListCommandsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<CommandResourceSchema, Fields>>, {
  results: Array<InferResult<CommandResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<CommandResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListCommandsConfig = {
  tenant?: string;
  fields: ListCommandsFields;
  filter?: CommandFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListCommandsResult<Fields extends ListCommandsFields, Page extends ListCommandsConfig["page"] = undefined> = | { success: true; data: InferListCommandsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Command records
 *
 * @ashActionType :read
 */
export async function listCommands<Fields extends ListCommandsFields, Config extends ListCommandsConfig = ListCommandsConfig>(
  config: Config & { fields: Fields }
): Promise<ListCommandsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_commands",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListCommandsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Command records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListCommands(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_commands",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateCommandInput = {
  name: string;
  shellCommand: string;
  cronExpression: string;
  enabled?: boolean;
  timeoutMs?: number;
  environmentId: UUID;
};

export type CreateCommandFields = UnifiedFieldSelection<CommandResourceSchema>[];

export type InferCreateCommandResult<
  Fields extends CreateCommandFields | undefined,
> = InferResult<CommandResourceSchema, Fields>;

export type CreateCommandResult<Fields extends CreateCommandFields | undefined = undefined> = | { success: true; data: InferCreateCommandResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Command
 *
 * @ashActionType :create
 */
export async function createCommand<Fields extends CreateCommandFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateCommandInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateCommandResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_command",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateCommandResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Command
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateCommand(
  config: {
  tenant?: string;
  input: CreateCommandInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_command",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateCommandInput = {
  name?: string;
  shellCommand?: string;
  cronExpression?: string;
  enabled?: boolean;
  timeoutMs?: number;
};

export type UpdateCommandFields = UnifiedFieldSelection<CommandResourceSchema>[];

export type InferUpdateCommandResult<
  Fields extends UpdateCommandFields | undefined,
> = InferResult<CommandResourceSchema, Fields>;

export type UpdateCommandResult<Fields extends UpdateCommandFields | undefined = undefined> = | { success: true; data: InferUpdateCommandResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Command
 *
 * @ashActionType :update
 */
export async function updateCommand<Fields extends UpdateCommandFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: UpdateCommandInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateCommandResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_command",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateCommandResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Command
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateCommand(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: UpdateCommandInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_command",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}



export type DestroyCommandResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Command
 *
 * @ashActionType :destroy
 */
export async function destroyCommand(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyCommandResult> {
  const payload = {
    action: "destroy_command",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyCommandResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Command
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyCommand(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "destroy_command",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type EnqueueCommandRunInput = {
  id: UUID;
};

export type InferEnqueueCommandRunResult = UUID;

export type EnqueueCommandRunResult = | { success: true; data: InferEnqueueCommandRunResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Command
 *
 * @ashActionType :action
 */
export async function enqueueCommandRun(
  config: {
  tenant?: string;
  input: EnqueueCommandRunInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<EnqueueCommandRunResult> {
  const payload = {
    action: "enqueue_command_run",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<EnqueueCommandRunResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Command
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateEnqueueCommandRun(
  config: {
  tenant?: string;
  input: EnqueueCommandRunInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "enqueue_command_run",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type EnqueueCommandRunInInput = {
  id: UUID;
  delaySeconds: number;
};

export type InferEnqueueCommandRunInResult = UUID;

export type EnqueueCommandRunInResult = | { success: true; data: InferEnqueueCommandRunInResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Command
 *
 * @ashActionType :action
 */
export async function enqueueCommandRunIn(
  config: {
  tenant?: string;
  input: EnqueueCommandRunInInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<EnqueueCommandRunInResult> {
  const payload = {
    action: "enqueue_command_run_in",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<EnqueueCommandRunInResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Command
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateEnqueueCommandRunIn(
  config: {
  tenant?: string;
  input: EnqueueCommandRunInInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "enqueue_command_run_in",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type EnqueueCommandRunForceInput = {
  id: UUID;
};

export type InferEnqueueCommandRunForceResult = UUID;

export type EnqueueCommandRunForceResult = | { success: true; data: InferEnqueueCommandRunForceResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Command
 *
 * @ashActionType :action
 */
export async function enqueueCommandRunForce(
  config: {
  tenant?: string;
  input: EnqueueCommandRunForceInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<EnqueueCommandRunForceResult> {
  const payload = {
    action: "enqueue_command_run_force",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<EnqueueCommandRunForceResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Command
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateEnqueueCommandRunForce(
  config: {
  tenant?: string;
  input: EnqueueCommandRunForceInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "enqueue_command_run_force",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RetryCommandLastFailedInput = {
  id: UUID;
};

export type InferRetryCommandLastFailedResult = UUID;

export type RetryCommandLastFailedResult = | { success: true; data: InferRetryCommandLastFailedResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Command
 *
 * @ashActionType :action
 */
export async function retryCommandLastFailed(
  config: {
  tenant?: string;
  input: RetryCommandLastFailedInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RetryCommandLastFailedResult> {
  const payload = {
    action: "retry_command_last_failed",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<RetryCommandLastFailedResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Command
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRetryCommandLastFailed(
  config: {
  tenant?: string;
  input: RetryCommandLastFailedInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "retry_command_last_failed",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListCommandExecutionEventsFields = UnifiedFieldSelection<CommandExecutionEventResourceSchema>[];


export type InferListCommandExecutionEventsResult<
  Fields extends ListCommandExecutionEventsFields | undefined,
  Page extends ListCommandExecutionEventsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<CommandExecutionEventResourceSchema, Fields>>, {
  results: Array<InferResult<CommandExecutionEventResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<CommandExecutionEventResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListCommandExecutionEventsConfig = {
  tenant?: string;
  fields: ListCommandExecutionEventsFields;
  filter?: CommandExecutionEventFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListCommandExecutionEventsResult<Fields extends ListCommandExecutionEventsFields, Page extends ListCommandExecutionEventsConfig["page"] = undefined> = | { success: true; data: InferListCommandExecutionEventsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read CommandExecutionEvent records
 *
 * @ashActionType :read
 */
export async function listCommandExecutionEvents<Fields extends ListCommandExecutionEventsFields, Config extends ListCommandExecutionEventsConfig = ListCommandExecutionEventsConfig>(
  config: Config & { fields: Fields }
): Promise<ListCommandExecutionEventsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_command_execution_events",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListCommandExecutionEventsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read CommandExecutionEvent records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListCommandExecutionEvents(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_command_execution_events",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListEventsForCommandInput = {
  commandId: UUID;
};

export type ListEventsForCommandFields = UnifiedFieldSelection<CommandExecutionEventResourceSchema>[];
export type InferListEventsForCommandResult<
  Fields extends ListEventsForCommandFields,
> = Array<InferResult<CommandExecutionEventResourceSchema, Fields>>;

export type ListEventsForCommandResult<Fields extends ListEventsForCommandFields> = | { success: true; data: InferListEventsForCommandResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read CommandExecutionEvent records
 *
 * @ashActionType :read
 */
export async function listEventsForCommand<Fields extends ListEventsForCommandFields>(
  config: {
  tenant?: string;
  input: ListEventsForCommandInput;
  fields: Fields;
  filter?: CommandExecutionEventFilterInput;
  sort?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListEventsForCommandResult<Fields>> {
  const payload = {
    action: "list_events_for_command",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort })
  };

  return executeActionRpcRequest<ListEventsForCommandResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read CommandExecutionEvent records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListEventsForCommand(
  config: {
  tenant?: string;
  input: ListEventsForCommandInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_events_for_command",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RetryCommandExecutionEventInput = {
  id: UUID;
};

export type InferRetryCommandExecutionEventResult = UUID;

export type RetryCommandExecutionEventResult = | { success: true; data: InferRetryCommandExecutionEventResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on CommandExecutionEvent
 *
 * @ashActionType :action
 */
export async function retryCommandExecutionEvent(
  config: {
  tenant?: string;
  input: RetryCommandExecutionEventInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RetryCommandExecutionEventResult> {
  const payload = {
    action: "retry_command_execution_event",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<RetryCommandExecutionEventResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on CommandExecutionEvent
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRetryCommandExecutionEvent(
  config: {
  tenant?: string;
  input: RetryCommandExecutionEventInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "retry_command_execution_event",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


